//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTime.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nonWorkingDay
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public bool AllowTimeLog { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreatedByUserId { get; set; }
        public string ModifiedByUserId { get; set; }
        public System.DateTime ModifyDateTime { get; set; }
    }
}
