//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTime.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeLog
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal Duration { get; set; }
        public System.DateTime Date { get; set; }
        public int ProjectUserId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifyDateTime { get; set; }
    
        public virtual project project { get; set; }
        public virtual projectUser projectUser { get; set; }
    }
}
