// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;


namespace ProjectTime_UITest.UserInterfaceTestcases
{
    [TestFixture]
    public class SuperUserTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> Vars { get; private set; }
        private IJavaScriptExecutor js;
        

        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            Vars = new Dictionary<string, object>();
            driver.Navigate().GoToUrl("https://projecttime-app.azurewebsites.net/");
            driver.Manage().Window.Size = new System.Drawing.Size(1600, 900);

        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        // UI Super User test case begins by logging in as a  super user role and logging out

        [Test, Order(1)]
        public void Test_SuperUserLogIn_LogOut()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.CssSelector(".btn-link")).Click();

        }

        // UI Super User test case begins by logging in as a Super user, clicks on the Add project Estimate button from the home page,
        //  and inputs required values and clicks on the create Button and completes

        [Test, Order(2)]
        public void Test_CreateProjectEstimate()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Add Project Estimate")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.Id("ProjectId"))).Click();
            driver.FindElement(By.Id("ProjectId")).SendKeys("Florence" + Keys.Enter);
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.Id("DepartmentId"))).Click();
            driver.FindElement(By.Id("DepartmentId")).SendKeys("Project Management Office" + Keys.Enter);
            driver.FindElement(By.Id("DateFrom")).Click();
            driver.FindElement(By.Id("DateFrom")).SendKeys("01-11-2022");
            driver.FindElement(By.Id("DateTo")).Click();
            driver.FindElement(By.Id("DateTo")).SendKeys("30-11-2022");
            driver.FindElement(By.Id("DurationDays")).Click();
            driver.FindElement(By.Id("DurationDays")).SendKeys("10");
            driver.FindElement(By.Id("Description")).Click();
            driver.FindElement(By.CssSelector(".container:nth-child(2)")).Click();
            driver.FindElement(By.Id("Description")).Click();
            driver.FindElement(By.Id("Description")).SendKeys("PMO duration required for Florence");
            driver.FindElement(By.CssSelector(".btn-primary")).Click();
        }

        // UI Super User test case begins by logging in as a Super user, navigates to My Projects drop-down and selects Project Estimate,
        // it clicks on the Project Estimate button, in the itemised Project estimate page it clicks on the edit button,
        // inputs required values and clicks on the Update Button and completes

        [Test, Order(3)]
        public void Test_EditProjectEstimate()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("My Projects")).Click();
            driver.FindElement(By.LinkText("Project Estimate")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.CssSelector(".even .btn"))).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.LinkText("Edit"))).Click();
            driver.FindElement(By.Id("DateTo")).Click();
            driver.FindElement(By.Id("DateTo")).Clear();
            driver.FindElement(By.Id("DateTo")).SendKeys("31-12-2022");
            driver.FindElement(By.Id("DurationDays")).Click();
            driver.FindElement(By.CssSelector(".border")).Click();
            driver.FindElement(By.Id("DurationDays")).SendKeys("20");
            driver.FindElement(By.Id("Description")).Click();
            driver.FindElement(By.Id("Description")).Clear();
            driver.FindElement(By.Id("Description")).SendKeys("PMO duration required for Florence updated");
            driver.FindElement(By.CssSelector(".btn-primary")).Click();
        }

        // UI Super User test case begins by logging in as a Super user, navigates to My Projects drop-down and selects Project Estimate,
        // it clicks on the Project Estimate button, in the itemised Project estimate page it clicks on the delete button,
        // it accepts the alert and completes

        [Test, Order(4)]
        public void Test_DeleteProjectEstimate()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("My Projects")).Click();
            driver.FindElement(By.LinkText("Project Estimate")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.CssSelector(".even .btn"))).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.CssSelector(".bi-trash-fill"))).Click();
            driver.FindElement(By.CssSelector(".btn-danger")).Click();
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            wait.Until(ExpectedConditions.AlertIsPresent());
            Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Are you sure you want to Delete this?"));
            driver.SwitchTo().Alert().Accept();
            driver.SwitchTo().ActiveElement().Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects ActualVEstimateEffortReport,
        // clicks on the copy button and copies reprt details to the clip board

        [Test, Order(5)]
        public void Test_ReportActualVEstimateEffort()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("Actual V Estimate Effort")).Click();
            driver.FindElement(By.CssSelector(".buttons-copy > span")).Click();

        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects ActualVEstimateSummaryReport,
        // clicks on the excel button to download the report in excel format

        [Test, Order(6)]
        public void Test_ReportActualVEstimateSummary()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("Actual V Estimate Summary")).Click();
            driver.FindElement(By.CssSelector(".buttons-excel > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects
        //ActualVEstimateVarianceReport, clicks on the csv button to download the report in csv format

        [Test, Order(7)]
        public void Test_ReportActualVEstimateVariance()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("Actual V Estimate Variance")).Click();
            driver.FindElement(By.CssSelector(".buttons-csv > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects AllTimeLogReport,
        // clicks on the pdf button to download the report in pdf

        [Test, Order(8)]
        public void Test_ReportAllTimeLog()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("All Time Logs")).Click();
            driver.FindElement(By.CssSelector(".buttons-pdf > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects TimeLogSummary,
        // clicks on the print button to open the printing dialog view

        [Test, Order(9)]
        public void Test_ReportTimeLogSummary()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("All Time Logs Summary")).Click();
            driver.FindElement(By.CssSelector(".buttons-print > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects Project Estimates,
        // enters Analysis into the Search bar to filter the report

        [Test, Order(10)]
        public void Test_ReportProjectEstimate()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.LinkText("Project Estimates"))).Click();
            driver.FindElement(By.CssSelector("input:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector("input:nth-child(1)")).SendKeys("Analysis");
            driver.FindElement(By.Id("tblDataprojectestimatereport_wrapper")).Click();
        }


        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects Project Estimate Summary,

        [Test, Order(11)]
        public void Test_ReportProjectEstimateSummary()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            driver.FindElement(By.LinkText("Project Estimate Summary")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects Rescourcing,
        // enters Analysis into the Search bar to filter the report

        [Test, Order(12)]
        public void Test_ReportRescourcing()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Reports")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.LinkText("Rescourcing"))).Click();
            driver.FindElement(By.CssSelector("input:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector("input:nth-child(1)")).SendKeys("Analysis");
            
        }


        //UI Super User test case begins by logging in as a Super user, navigates to the My Projects drop-down and selects Project Tracking,
        // clicks on the excel button to download the report in excel format

        [Test, Order(13)]
        public void Test_ProjectTracking()
        {

            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("My Projects")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.LinkText("Project Tracking"))).Click();
            driver.FindElement(By.CssSelector(".buttons-excel > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects Project Tracking,
        // navigates and click on the Project Tracking Effort button then clicks on the pdf button to download the report in pdf

        [Test, Order(14)]
        public void Test_ProejctTrackingEffort()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("My Projects")).Click();
            driver.FindElement(By.LinkText("Project Tracking")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.CssSelector(".btn-primary:nth-child(1) > .bi"))).Click();
            driver.FindElement(By.CssSelector(".buttons-pdf > span")).Click();
        }

        //UI Super User test case begins by logging in as a Super user, navigates to the Reports drop-down and selects Project Tracking,
        // navigates and click on the Project Tracking Variance button then clicks on the csv button to download the report in csv

        [Test, Order(15)]
        public void Test_ProejctTrackingVariance()
        {
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Input_Email")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("superuser@projecttime.ie");
            driver.FindElement(By.Id("Input_Password")).Click();
            driver.FindElement(By.Id("Input_Password")).SendKeys("Coding@1234!");
            driver.FindElement(By.Id("Input_Password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("My Projects")).Click();
            driver.FindElement(By.LinkText("Project Tracking")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until(ExpectedConditions.ElementToBeClickable(By.LinkText("Variance"))).Click();
            driver.FindElement(By.CssSelector(".buttons-csv > span")).Click();
        }




    }
}